# Generated by Django 4.1.5 on 2023-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='technology_logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_uil_name',
            field=models.CharField(default='vedio', max_length=100),
        ),
    ]
