# Generated by Django 4.1.5 on 2023-02-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_technology_technology_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_github_url',
            field=models.URLField(default='https://github.com', null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology_uil_name',
            field=models.CharField(default='brackets-curly', max_length=100),
        ),
    ]
