# Generated by Django 4.1.5 on 2023-02-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_softskill_remove_blog_comments_remove_blog_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
